[tool.bumpversion]
current_version = "1.0.1-moz.1.1"
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)-moz\\.(?P<fork_minor>\\d+)\\.(?P<fork_patch>\\d+)"
serialize = ["{major}.{minor}.{patch}-moz.{fork_minor}.{fork_patch}"]
search = "{current_version}"
replace = "{new_version}"
regex = false
ignore_missing_version = false
ignore_missing_files = false
tag = false
sign_tags = false
tag_name = "v{new_version}"
tag_message = "Bump version: {current_version} → {new_version}"
allow_dirty = false
commit = true
message = "Bump version: {current_version} → {new_version}"
moveable_tags = []
commit_args = "--no-verify"
setup_hooks = []
pre_commit_hooks = []
post_commit_hooks = []

[tool.bumpversion.parts.fork_minor]
independent = true
first_value = "0"

[tool.bumpversion.parts.fork_patch]
first_value = "0"

[[tool.bumpversion.files]]
filename = "config/settings/base.py"
search = "APP_VERSION_NUMBER = \"{current_version}\""
replace = "APP_VERSION_NUMBER = \"{new_version}\""

[[tool.bumpversion.files]]
filename = "offgridplanner/__init__.py"

[[tool.bumpversion.files]]
filename = "CHANGELOG.md"
search = "## [Unreleased]"
replace = """## [Unreleased]

## [v{new_version}] – {now:%Y-%m-%d}"""
